services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: nmc-website-prod
    container_name: nmc-website-prod-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/
      - /etc/letsencrypt/:/etc/letsencrypt
    env_file:
      - ./id.env
