services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: nmc-website-prod
    container_name: nmc-website-prod-container
    hostname: newmediacaucus.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/
      - ./custom-php.prod.ini:/etc/php/8.3/apache2/conf.d/custom-php.ini
      - ./php-logs:/var/log/php-logs
      - ./apache-logs:/var/log/apache2
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - ./id.env
    depends_on:
      - certbot
    networks:
      - webnet

  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    image: nmc-website-certbot
    container_name: certbot
    user: root
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt-logs:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nmcdev/nmc-website:/var/www/html
    environment:
      - DOMAIN=newmediacaucus.org
      - EMAIL=admin@newmediacaucus.org
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: nmc-website_webnet