title: New Media Caucus

sections:

  pages:
    label: Nested Sections
    help: Panel user section
    templates:
    # order is inhereted from folder numbering
      - people
      - blog
      - opportunities
      - about
      - initiatives
      - gallery
        
  all:
    label: All Pages
    help: Dev section
    type: pages
    status: all
    layout: list

