title: New Media Caucus

sections:

  pages:
    label: Nested Sections
    help: Panel user section
    templates:
    # order is inhereted from folder numbering
      - people
      - blog
      - opportunities
      - about
      - initiatives
        
  all:
    label: All Pages
    help: Dev section
    type: pages
    status: all
    layout: list

  header_footer_gallery:
    label: Header/Footer Gallery
    type: pages
    parent: site.find("header-footer-gallery")
    layout: list 
    templates: show
    sortBy: date desc
    help: "Sorted newest at the top."

