title: New Media Caucus

tabs:
  tab1:
    label: Panel Editors
    icon: edit
    sections:
      paneleditors:
        type: pages
        label: Sections
        templates:
            # order is inhereted from folder numbering
              - people
              - blog
              - opportunities
              - about
              - initiatives
              - gallery
  tab2:  
    label: Dev Editors
    icon: lab
    sections:
      deveditors:
        type: pages
        label: Dev Editors
        templates:
            # order is inhereted from folder numbering
              - link