title: Site

sections:

  all:
    label: Main Pages
    type: pages
    status: all
    layout: list

  opportunities:
    label: Opportunities
    type: pages
    parent: site.find("opportunities")
    layout: list   
