title: New Media Caucus

sections:

  all:
    label: Main Pages
    type: pages
    status: all
    layout: list

  opportunities:
    label: Opportunities
    type: pages
    parent: site.find("opportunities")
    layout: list 
    templates: opportunity
    # https://getkirby.com/docs/reference/panel/sections/pages
    sortBy: date desc
    help: "Sorted newest at the top."
    
  about:
    label: About Us
    type: pages
    parent: site.find("about-us")
    layout: list 
    templates: human
    sortBy: title asc
    help: "Sorted alphabetically by first name."

  initiatives:
    label: Our Initiatives
    type: pages
    parent: site.find("our-initiatives")
    layout: list 
    templates: initiative
    sortBy: date desc
    help: "Sorted newest at the top."

