<!-- top section -->
<?php snippet('header') ?>

<!-- nav section -->
<?php snippet('navigation') ?>

<!-- content section -->
<?php snippet('header') ?>

<main>

  <p><?= $page->welcome()->kirbytext() ?></p>
  <!-- section name -->
  <div class="opportunities-title">
    <h1>Latest News</h1>
  </div>

  <?php
  // Setup filters for each category. Note: tag filtering is case sensitive.
  $blog = $site->find('blog')->children();
  $blog_news_list = $blog->filterBy('tags', 'News', ',')->limit(3);

  $opportunities = $site->find('opportunities')->children();
  $opps_news_list = $opportunities->limit(3);
  ?>

  <div class="opportunities">
    <!-- latest blog news items -->
    <?php foreach ($blog_news_list as $blog_news_item): ?>

      <!-- image section -->
      <?php if ($image = $blog_news_item->image()): ?>
        <div class="opportunity">
          <div class="post-image">
            <a href="<?= $blog_news_item->url() ?>">
              <!-- grab first image in project folder (alphabetically) -->
              <img src="<?= $image->crop(960)->url() ?>" alt="<?= $blog_news_item->alt() ?>">
            </a>
          </div>
          <!-- text section -->
          <div class="post">
            <!-- post title -->
            <a href="<?= $blog_news_item->url() ?>">
              <h2><?= $blog_news_item->Title() ?></h2>
            </a>
            <!-- list individual post tags -->
            <!-- https://forum.getkirby.com/t/list-tags-for-a-page/31301 -->
            <?php $post_tags = $blog_news_item->tags()->split() ?>
            <?php foreach ($post_tags as $post_tag): ?>
              <a class="category" href="<?= url('blog', ['params' => ['tag' => $post_tag]]) ?>">
                <?= $post_tag ?>
              </a>
            <?php endforeach ?>

            <!-- Display posted date -->
            <div class="posted-date">
              Posted <?= $blog_news_item->date()->toDate('F j, Y') ?>
            </div>
            <!-- text excerpt (autogenerated) -->
            <p><?= $blog_news_item->text()->excerpt(300) ?></p>
            <!-- Read More Button -->
            <a href="<?= $blog_news_item->url() ?>" class="button">
              View Post
            </a>

          </div>
        </div>
      <?php endif ?>
    <?php endforeach ?>
  </div>

  <!-- section name -->
  <div class="opportunities-title">
    <h1>Latest Opportunities</h1>
  </div>
  <div class="opportunities">
    <?php foreach ($opps_news_list as $opps_news_item): ?>
      <!-- latest opportunities posts-->

      <!-- image section -->
      <?php if ($image = $opps_news_item->image()): ?>
        <div class="opportunity">
          <div class="post-image">
            <a href="<?= $opps_news_item->url() ?>">
              <!-- grab first image in project folder (alphabetically) -->
              <img src="<?= $image->crop(960)->url() ?>" alt="<?= $opps_news_item->alt() ?>">
            </a>
          </div>
          <!-- text section -->
          <div class="post">
            <!-- post title -->
            <a href="<?= $opps_news_item->url() ?>">
              <h2><?= $opps_news_item->Title() ?></h2>
            </a>
            <!-- list individual post tags -->
            <!-- https://forum.getkirby.com/t/list-tags-for-a-page/31301 -->
            <?php $post_tags = $opps_news_item->tags()->split() ?>

            <?php foreach ($post_tags as $post_tag): ?>
              <a class="category" href="<?= url('opportunities', ['params' => ['tag' => $post_tag]]) ?>">
                <?= $post_tag ?>
              </a>
            <?php endforeach ?>

            <!-- Display posted date -->
            <div class="posted-date">
              Posted <?= $opps_news_item->date()->toDate('F j, Y') ?>
            </div>
            <!-- Display short description -->
            <p class="description"><?= $opps_news_item->short_description()->kirbytext() ?></p>
            <!-- Read More Button -->
            <a href="<?= $opps_news_item->url() ?>" class="button">
              View Post
            </a>
          </div>
        </div>
      <?php endif ?>
    <?php endforeach ?>
  </div>

  <!-- Submit an opportunity promo -->
  <div class="promo">📣 <a href="https://docs.google.com/forms/d/e/1FAIpQLSczR9Ct3qaWETS72DoIO03LlLTeIWF8sSQxMvnTNwfs0aXAHA/viewform">Got an Opportunity? Post It!</a> 🦄</div>

</main>

<!-- bottom section -->
<?php snippet('footer') ?>